SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS USER_ALARM_SETTING;
DROP TABLE IF EXISTS ALARM;
DROP TABLE IF EXISTS CHATTING;
DROP TABLE IF EXISTS USER_CHAT;
DROP TABLE IF EXISTS CHATROOM;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS MESSAGE_CMT;
DROP TABLE IF EXISTS USER_MESSAGE;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS EVENT_KEY;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS PREFERENCE_SUB;
DROP TABLE IF EXISTS USER_PREFERENCE;
DROP TABLE IF EXISTS PREFERENCE;
DROP TABLE IF EXISTS USER_LOCATION_LOG;
DROP TABLE IF EXISTS USER_PUSH;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS UTIL_APPS;




/* Create Tables */

CREATE TABLE ALARM
(
	ALARM_ID int NOT NULL,
	Description varchar(128),
	PRIMARY KEY (ALARM_ID)
);


CREATE TABLE CHATROOM
(
	CHATROOM_ID bigint NOT NULL,
	CREATE_DATE datetime,
	USER_CNT int,
	PRIMARY KEY (CHATROOM_ID)
);


CREATE TABLE CHATTING
(
	CHATROOM_ID bigint NOT NULL,
	CHATTING_ID bigint NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	MSG varchar(1024),
	READ_CNT int,
	CREATE_DATE datetime,
	PRIMARY KEY (CHATROOM_ID, CHATTING_ID)
) COMMENT = '여기는 안읽은 메세지만 쌓이는 DB

Chatting 내용은 무조건 안드로이드 내부 db에 저장하여 볼 ';


CREATE TABLE CONFIG
(
	CONFIG_ID int NOT NULL,
	CONFIG_VALUE varchar(128),
	Description varchar(256),
	PRIMARY KEY (CONFIG_ID)
);


CREATE TABLE EVENT
(
	EVENT_ID bigint NOT NULL,
	EVENT_TITLE varchar(128),
	EVENT_BODY varchar(300),
	EVENT_IMG varchar(200),
	PRIMARY KEY (EVENT_ID)
);


CREATE TABLE EVENT_KEY
(
	EVENT_ID bigint NOT NULL,
	EVENT_KEY bigint NOT NULL,
	VALUE varchar(64),
	PRIMARY KEY (EVENT_KEY)
);


CREATE TABLE MESSAGE
(
	MESSAGE_ID bigint NOT NULL,
	MESSAGE_TYPE int COMMENT '관리자가 광고/이벤트식으로 올렸는지, 
사용자가 메시지를 생성한것인지',
	CREATE_DATE datetime,
	ACCESS_CNT int,
	EVENT_KEY bigint NOT NULL,
	PRIMARY KEY (MESSAGE_ID)
);


CREATE TABLE MESSAGE_CMT
(
	MESSAGE_ID bigint NOT NULL,
	MESSAGE_CMT_ID bigint NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	CMT varchar(300),
	CREATE_DATE datetime,
	PRIMARY KEY (MESSAGE_ID, MESSAGE_CMT_ID)
);


CREATE TABLE PREFERENCE
(
	PREFER_ID int NOT NULL,
	Description varchar(256),
	PRIMARY KEY (PREFER_ID)
);


CREATE TABLE PREFERENCE_SUB
(
	PREFER_ID int NOT NULL,
	PREFER_SUB_ID int NOT NULL,
	PREFER_SUB_NM varchar(64),
	VALUE varchar(64),
	PRIMARY KEY (PREFER_ID, PREFER_SUB_ID)
);


CREATE TABLE USER
(
	USER_TOKEN varchar(128) NOT NULL,
	USER_ID varchar(20) NOT NULL,
	USER_NM varchar(20),
	USER_IMG varchar(128),
	USER_MAIL varchar(50),
	USER_AUTH int COMMENT '
',
	USER_AGE int,
	USER_CONTRY varchar(30),
	USER_PROFILE varchar(300),
	PRIMARY KEY (USER_TOKEN)
);


CREATE TABLE USER_ALARM_SETTING
(
	ALARM_ID int NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	Value int,
	PRIMARY KEY (ALARM_ID, USER_TOKEN)
);


CREATE TABLE USER_CHAT
(
	CHATROOM_ID bigint NOT NULL,
	POSS_AUTH int,
	ALARM int,
	USER_TOKEN varchar(128) NOT NULL,
	PRIMARY KEY (CHATROOM_ID, USER_TOKEN)
);


CREATE TABLE USER_LOCATION_LOG
(
	LOCATION_ID bigint NOT NULL,
	LAT double,
	LON double,
	CREATE_DATE datetime,
	USER_TOKEN varchar(128) NOT NULL,
	PRIMARY KEY (LOCATION_ID)
);


CREATE TABLE USER_MESSAGE
(
	MESSAGE_ID bigint NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	POSS_AUTH int,
	ALARM int,
	REQUEST_STATUS int,
	REQUEST_CMT varchar(512),
	PRIMARY KEY (MESSAGE_ID, USER_TOKEN)
);


CREATE TABLE USER_PREFERENCE
(
	PREFER_ID int NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	PRIORITY int,
	VALUE varchar(64),
	PRIMARY KEY (PREFER_ID, USER_TOKEN)
);


CREATE TABLE USER_PUSH
(
	PUSH_ID varchar(255) NOT NULL,
	USER_TOKEN varchar(128) NOT NULL,
	PRIMARY KEY (PUSH_ID, USER_TOKEN)
);


CREATE TABLE UTIL_APPS
(
	APP_ID int NOT NULL,
	APP_NAME varchar(64),
	APP_LINK varchar(512),
	Description varchar(1024),
	PRIMARY KEY (APP_ID)
);



/* Create Foreign Keys */

ALTER TABLE USER_ALARM_SETTING
	ADD FOREIGN KEY (ALARM_ID)
	REFERENCES ALARM (ALARM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CHATTING
	ADD FOREIGN KEY (CHATROOM_ID)
	REFERENCES CHATROOM (CHATROOM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_CHAT
	ADD FOREIGN KEY (CHATROOM_ID)
	REFERENCES CHATROOM (CHATROOM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EVENT_KEY
	ADD FOREIGN KEY (EVENT_ID)
	REFERENCES EVENT (EVENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (EVENT_KEY)
	REFERENCES EVENT_KEY (EVENT_KEY)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE_CMT
	ADD FOREIGN KEY (MESSAGE_ID)
	REFERENCES MESSAGE (MESSAGE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_MESSAGE
	ADD FOREIGN KEY (MESSAGE_ID)
	REFERENCES MESSAGE (MESSAGE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PREFERENCE_SUB
	ADD FOREIGN KEY (PREFER_ID)
	REFERENCES PREFERENCE (PREFER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_PREFERENCE
	ADD FOREIGN KEY (PREFER_ID)
	REFERENCES PREFERENCE (PREFER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CHATTING
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE_CMT
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_ALARM_SETTING
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_CHAT
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_LOCATION_LOG
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_MESSAGE
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_PREFERENCE
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_PUSH
	ADD FOREIGN KEY (USER_TOKEN)
	REFERENCES USER (USER_TOKEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



